# Generated by Django 4.2.5 on 2023-10-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0002_rename_name_organization_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('-1', 'Rejected')], default='0', max_length=100)),
                ('requested_role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_promotion_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='org.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Request',
                'verbose_name_plural': 'Promotion Requests',
                'db_table': 'promotion_requests',
            },
        ),
    ]
