# Generated by Django 4.2.5 on 2023-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Hide'), ('-1', 'Deleted')], default='1', max_length=100),
        ),
    ]
