# Generated by Django 4.2.5 on 2023-10-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='title',
        ),
    ]
